services: couchdb
language: elixir

matrix:
  include:
    - elixir: 1.2.6
      otp_release: 18.3
    - elixir: 1.2.6
      otp_release: 19.3
    - elixir: 1.3.4
      otp_release: 18.3
    - elixir: 1.3.4
      otp_release: 19.3
    - elixir: 1.4.5
      otp_release: 18.3
    - elixir: 1.4.5
      otp_release: 19.3
    - elixir: 1.4.5
      otp_release: 20.0

env:
  - MIX_ENV=test

script: mix coveralls.travis
